### ISSUE TITLE
Build failed - failed to run custom build command for `openssl-sys v0.6.4`

### ISSUE THREAD

**Issue by groovy354** [witheve/Eve#208]
After successfully installing all the dependency that run.sh asked for and running run.sh again, I get this response:
```
(...)
   Compiling hpack v0.2.0
Build failed, waiting for other jobs to finish...
failed to run custom build command for `openssl-sys v0.6.4`
Process didn't exit successfully: `/home/kuba/temp/Eve/runtime/target/debug/build/openssl-sys-765ddf9de3c5179c/build-script-build` (exit code: 101)
--- stdout
cargo:rustc-link-lib=dylib=crypto
cargo:rustc-link-lib=dylib=ssl
TARGET = Some("x86_64-unknown-linux-gnu")
TARGET = Some("x86_64-unknown-linux-gnu")
CARGO_MANIFEST_DIR = Some("/home/kuba/.multirust/toolchains/nightly-2015-08-10/cargo/registry/src/github.com-0a35038f75765ae4/openssl-sys-0.6.4")
OUT_DIR = Some("/home/kuba/temp/Eve/runtime/target/debug/build/openssl-sys-765ddf9de3c5179c/out")
OPT_LEVEL = Some("0")
PROFILE = Some("debug")
debug 0
TARGET = Some("x86_64-unknown-linux-gnu")
HOST = Some("x86_64-unknown-linux-gnu")
CC_x86_64-unknown-linux-gnu = None
CC_x86_64_unknown_linux_gnu = None
HOST_CC = None
CC = None
TARGET = Some("x86_64-unknown-linux-gnu")
HOST = Some("x86_64-unknown-linux-gnu")
CFLAGS_x86_64-unknown-linux-gnu = None
CFLAGS_x86_64_unknown_linux_gnu = None
HOST_CFLAGS = None
CFLAGS = None
running: "cc" "-O0" "-c" "-ffunction-sections" "-fdata-sections" "-g" "-m64" "-fPIC" "-o" "/home/kuba/temp/Eve/runtime/target/debug/build/openssl-sys-765ddf9de3c5179c/out/src/openssl_shim.o" "/home/kuba/.multirust/toolchains/nightly-2015-08-10/cargo/registry/src/github.com-0a35038f75765ae4/openssl-sys-0.6.4/src/openssl_shim.c"


command did not execute successfully, got: exit code: 1



--- stderr
/home/kuba/.multirust/toolchains/nightly-2015-08-10/cargo/registry/src/github.com-0a35038f75765ae4/openssl-sys-0.6.4/src/openssl_shim.c:1:26: fatal error: openssl/hmac.h: No such file or directory
 #include <openssl/hmac.h>
                          ^
compilation terminated.
thread '<main>' panicked at 'explicit panic', /home/kuba/.multirust/toolchains/nightly-2015-08-10/cargo/registry/src/github.com-0a35038f75765ae4/gcc-0.3.11/src/lib.rs:514
stack backtrace:
   1:     0x7f71a300ea6e - sys::backtrace::write::h7f613ce09e7b1d1d5As
   2:     0x7f71a30173f6 - panicking::on_panic::he6322b413efd100fGFx
   3:     0x7f71a2fd79ce - rt::unwind::begin_unwind_inner::h16a4850d896eee23R6w
   4:     0x7f71a37aeb1c - rt::unwind::begin_unwind::h17421284490640175071
                        at ../src/libstd/rt/unwind/mod.rs:236
   5:     0x7f71a37a8140 - fail::hf0d4f1ca6d7a5404COa
                        at /home/kuba/temp/Eve/runtime/<std macros>:3
   6:     0x7f71a37b7ea3 - run::h7be3ffcf524eddceKHa
                        at /home/kuba/.multirust/toolchains/nightly-2015-08-10/cargo/registry/src/github.com-0a35038f75765ae4/gcc-0.3.11/src/lib.rs:485
   7:     0x7f71a37b1a2a - Config::compile_object::h661499c1644adb0aema
                        at /home/kuba/.multirust/toolchains/nightly-2015-08-10/cargo/registry/src/github.com-0a35038f75765ae4/gcc-0.3.11/src/lib.rs:276
   8:     0x7f71a37ab5ea - Config::compile::hd820e5738d396b0eRha
                        at /home/kuba/.multirust/toolchains/nightly-2015-08-10/cargo/registry/src/github.com-0a35038f75765ae4/gcc-0.3.11/src/lib.rs:233
   9:     0x7f71a377b079 - build_openssl_shim::h4ca03af19d6db933Sfa
                        at /home/kuba/.multirust/toolchains/nightly-2015-08-10/cargo/registry/src/github.com-0a35038f75765ae4/openssl-sys-0.6.4/build.rs:75
  10:     0x7f71a3774a33 - main::h53a555fd2c70138diaa
                        at /home/kuba/.multirust/toolchains/nightly-2015-08-10/cargo/registry/src/github.com-0a35038f75765ae4/openssl-sys-0.6.4/build.rs:65
  11:     0x7f71a3016c5d - __rust_try
  12:     0x7f71a30191ca - rt::lang_start::h996e83640adddea1BAx
  13:     0x7f71a3782f0b - main
  14:     0x7f71a2751a3f - __libc_start_main
  15:     0x7f71a37733b8 - _start
  16:                0x0 - <unknown>

```

**Comment by joshuafcole** [comment]
We're investigating if we can remove the sub-dependency on OpenSSL, since we don't use it directly, nor do we use any features which rely on it's existence. In the interim, you can investigate using steve's suggestion to link against an existing OpenSSL installation. https://github.com/witheve/Eve/issues/190#issuecomment-131980782

**Comment by ibdknox** [comment]
I think this will fix it for the linux folks:

```
apt-get install openssl-dev
```

**Comment by jamii** [comment]
Unfortunately openssl is not an optional feature in rust-websocket, so removing the dependency is not as simple as I hoped.

**Comment by groovy354** [comment]
@ibdknox I get
```
E: Unable to locate package openssl-dev
```

Should I add a specific ppa repository?

**Comment by ibdknox** [comment]
Ah sorry, it's `libssl-dev`:

```
sudo apt-get install libssl-dev 
```

**Comment by groovy354** [comment]
It helped, thank you!

**Comment by thomas-shares** [comment]
Would it be possible to add this as a test in one of the build scripts. a check to make sure all pre-reqs are installed? I just ran into this as well.

**Comment by joshuafcole** [comment]
Hey @thomas-shares, this isn't actually a prereq of Eve (or even of the rust crate that's pulling it in -- it's supposed to be able to build it's own local version if it can't find a system version). We're looking into statically linking our own version of SSL in to prevent this from cropping up in the future, since it's build chain for SSL seems to be very flaky.

**Comment by thomas-shares** [comment]
Hi @joshuafcole ,
Thank you for your response. In my opinion if the build fails because something isn't installed, that makes it a pre-req :)
If it actually not needed or subsequently used it should be removed. Now I understand that this is easier said than done, so it might take more effort to remove it compared to adding a test to make sure it is there. I would be happy with either way, what ever is easiest for you guys.

And thank you for this exciting new product you guys are working on, it looks really interesting.

**Comment by joshuafcole** [comment]
Ah, sorry I wasn't clear. I meant to say that a) we don't use it, but also (and more importantly) b) the rust crate that depends on it has a build script to compile and link against it's own internal version of OpenSSL in the event that there isn't a system one installed. So nobody should have to have a system version installed, the issue is just that the crate's build script is flaky.

Rather than requiring users to install and maintain their distro's version of OpenSSL, we're planning to statically link it to a binary we create in the next major version so we don't have to rely on the faulty build script anymore.

Cheers,
Josh

**Comment by thomas-shares** [comment]
ok sounds good. thank you.
