### ISSUE TITLE
Add a way to export query results (possibly in a .CSV format)

### ISSUE THREAD

**Issue by tenkabuto** [witheve/Eve#241]

**Comment by joshuafcole** [comment]
Yeah, we agree that this needs to happen. We think it may be better to hold off on this until we've added generic support for external inputs and actions. However, if somebody would like to contribute this as an action in the query toolbar using papaparse to export the results, I'd be happy to accept it.

**Comment by dumblob** [comment]
@joshuafcole will the *generic support for external inputs and actions* contain also some visualization (e.g. clickable break-downs visualized in beautiful charts)?

My goal is to try to use Eve instead of LO Calc or Excel, so I'm interested in the whole workflow chain (input, processing, visual output in 2 forms - a colored table and charts).

**Comment by joshuafcole** [comment]
We expect simple charts and other visualizations will land even earlier. At the moment we're focused primarily on shoring up the language underpinnings, but we'll make sure to post news in the eve talk mailing list about work on the editing experience.

**Comment by dumblob** [comment]
Any references where and how the issue has been solved?

**Comment by cmontella** [comment]
dumblob,

CSV export was added to the REPL at this point: https://github.com/witheve/Eve/tree/90a6c6bc4597572a29c72119fc7bb964426f8107

You can read a little about the REPL here: http://incidentalcomplexity.com/2016/06/22/mar2/

The REPL is being refactored, so CSV export will need to be added back, but the code is there.

Corey
