### ISSUE TITLE
What ports Eve uses?

### ISSUE THREAD

**Issue by salmazov** [witheve/Eve#259]
I want to start up server in Azure. I opened port 8080, but Eve not running. I see blank page on my screen.

What ports I should open?

**Comment by salmazov** [comment]
So I see this error in my log:
Warning: serve error Error { repr: Os { code: 32, message: "Broken pipe" } }

**Comment by salmazov** [comment]
Warning, cannot migrate state for: "a582cf23-4c9b-43c1-9d35-6c2c248e30a0"

**Comment by bjtitus** [comment]
I believe that 8080 and 2794 are the two default ports but 8080 should be all you need to at least see the web interface.

**Comment by salmazov** [comment]
I checked and solved problem myself. This is port 8080 and 2794. And they are both needed.

**Comment by cmontella** [comment]
Glad you solved this yourself. For clarification as to why there are two ports: 2794 is for the Eve runtime, while 8080 is used for the static file server. When you connect to the Eve UI, you connect to 8080, which opens a websocket connection to the runtime at 2794.

We've made the static file server port configurable, since 8080 is a common port. We will eventually make the fileserver port configurable too.

Also, the warning you saw is fine for now: it is raised in the case that output fields change.
