### ISSUE TITLE
Authentication ideas and services

### ISSUE THREAD

**Issue by dumblob** [witheve/Eve#350]
I've noticed notes about authentication on https://github.com/witheve/Eve/blob/master/design/io.md#authentication-and-identity and I think the project shouldn't be dependent on a proprietary service like AuthRocket. There are very good open-source options:

* Keycloak (Identity and Access Management for Modern Applications, Services and APIs, login service)
* JOSSO 2 Identity Management, Access Management and Single Sign-On system

In case proprietary service will be needed (hopefully not) , I can recommend Atlassian Crowd identity mgmt (it should be free for open-source, and non-profit projects and for school classrooms).

**Comment by dumblob** [comment]
How does the authentication look like in the end? How was the issue of dependency on a proprietary service solved?

**Comment by cmontella** [comment]
dumblob,

We currently don't have a strategy for authentication -- the core of the system has changed so much since we used AuthRocket, that we have to revisit the fundamentals of what authentication is for our system. I appreciate your sentiment about openness, though, and I believe you are right that an open source project should not depend on a proprietary service. When we revisit the issue, I will keep that in mind.

Corey

**Comment by dumblob** [comment]
Thanks for explanation.
