### ISSUE TITLE
npm run dev fails on Windows 10

### ISSUE THREAD

**Issue by code-recipes** [witheve/Eve#364]
Hi, I get the error below when running >npm run dev
[
![image](https://cloud.githubusercontent.com/assets/20109071/16706255/a8a12194-45d7-11e6-8497-111fb365221b.png)
](url)

**Comment by ExMateria** [comment]
I got this error as well in Windows 10.

I installed node-gyp https://github.com/nodejs/node-gyp#installation

and that moved me to the following error

![cmd_2016-07-12_23-44-05](https://cloud.githubusercontent.com/assets/1392539/16792977/b0a802f8-488a-11e6-80d1-dd7753523f68.png)

**Comment by cmontella** [comment]
Hey, thanks for taking the time to file this. We've never tested the code you're trying to run against Windows, so this is not unexpected. However, I'm going to mark this issue as "won't fix" because we are currently working on another codebase (witheve/lueve), which we will actually be merging into witheve/eve tomorrow (hopefully). That codebase doesn't depend on Node at all, so this issue will be moot. 

We do have a Docker container for running under Windows (see witheve/lueve). We'll also be releasing binaries soon, so you won't have to worry about building it.
