### ISSUE TITLE
Combination of #session-connect firing only on refresh and refresh potentially clobbering editor state makes using the editor an uncomfortable experience

### ISSUE THREAD

**Issue by frankier** [witheve/Eve#433]
Steps to reproduce

1. Run `$ eve examples/flappy.eve`.

2. Change the line
`[#svg @game-window viewBox: "10 0 80 100", width: 480 children:`
to
`[#svg @game-window viewBox: "10 0 80 100", width: 50 children:`

3. Click "compile and run".

Expected behaviour:
Output canvas appears smaller.

Actual behaviour:
No visible change.

Workaround:
1. Click "save"
2. Refresh

**Comment by frankier** [comment]
Browser: Chromium Version 51.0.2704.79
OS: Ubuntu 16.04
Eve version: ec213e7e884cd5e3aa8323dfd6c8c53e8163c4d6

**Comment by frankier** [comment]
Okay I think I've now realised this is by design? I guess what makes this confusing is although often for live coding you don't want @session-connect to refire, sometimes you do. Actually refreshing the whole page feels weird since the page also holds the editor state which is only persisted on save. I know eventually the plan is to have editor undo/redo hardwired so this won't seem as odd. An interim solution might be to put a refresh button on the right pane to just refresh the app and not the editor.

**Comment by joshuafcole** [comment]
Hey @frankier, it seems like you've already come to the same conclusions we have. I certainly agree that the current behavior is clunky, but it is intentional. We're currently rebuilding the editor from scratch and should be able to provide a much smoother experience as part of that.

If you have any repro cases in which the editor's contents are clobbered on refresh, please create a new issue for those--losing user's work is all kinds of bad--and I'll look into them immediately.
