### ISSUE TITLE
Divergence errors are printed to the developer console rather than displayed in the error panel

### ISSUE THREAD

**Issue by frankier** [witheve/Eve#435]
Divergence errors are printed to the developer console rather than displayed in the error panel. It took me a while to figure out that they were there. You can reproduce this using eg eve examples/divergent-in-f.eve . I guess these should be displayed in the same place as other errors.

**Comment by joshuafcole** [comment]
Yep, this is known. They come in through a side channel (since the entire Eve instance is compromised at the moment under divergence scenarios). In the near future, Eve will evaluate compiler/editor queries in a completely separate thread from user code, so we should be able to deal with them naturally along with the normal errors. Expect to see this fixed in the next release, but I'll keep this open to track it's progress.

**Comment by cmontella** [comment]
This is fixed in 0.2
