### ISSUE TITLE
Docker dev environment?

### ISSUE THREAD

**Issue by runvnc** [witheve/Eve#451]
Is there a way to take advantage of the docker container for development?  It isn't necessarily that hard to set up the stuff manually, but can we run the container and then load the Eve environment inside of it and do development in there?  If so, what are the commands.

Thanks for your time.

**Comment by cmontella** [comment]
I don't understand Docker that well, so maybe you could explain what you're trying to accomplish and I can help from there. It's my understanding if you wanted to work inside the Docker environment you'd need a different entry into the container. Right now it points to `./eve`, but I think you'd want it to load a shell, and from there it would work like a CLI.

For reference, here is the Dockerfile:

```
FROM ubuntu:14.04
MAINTAINER Kodowa, Inc. <info@kodowa.com>
ADD /eve /eve
ADD /luajit /luajit
RUN apt-get update && apt-get install -y \
    python \
    gcc \
    make
WORKDIR /luajit
RUN make && make install
RUN ln -sf luajit-2.1.0-beta2 /usr/local/bin/luajit
WORKDIR /eve/build
RUN make
EXPOSE 8080
ENTRYPOINT ["./eve"]
```

I think removing that last line would do the trick.

**Comment by SeeThruHead** [comment]
It might be nice to provide a docker-compose.yml that sets up the dev environment, env vars, volume mounts, then runs the compiled eve binary.

you could even mount the local FS and use the code from there rather than adding the code to the docker image every build.

docker-compose.yml
```
version: '2'
services:
  eve:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: ./eve
    ports:
      - '8080:8080'
    volumes:
      - ".:/eve"
```

Dockerfile.dev
```
FROM ubuntu:14.04
MAINTAINER Kodowa, Inc. <info@kodowa.com>
ADD /luajit /luajit
RUN apt-get update && apt-get install -y \
    python \
    gcc \
    make
WORKDIR /luajit
RUN make && make install
RUN ln -sf luajit-2.1.0-beta2 /usr/local/bin/luajit
WORKDIR /eve/build
RUN make
EXPOSE 8080
```
might not work (haven't tested it) but it could help

**Comment by cmontella** [comment]
Thanks for the tip! I'll take a look at what this does.

**Comment by cmontella** [comment]
I've updated the docker image yesterday, there's a docker-compose.yml as well. They've been added to the repo, and we can evolve them from here.

In terms of a docker dev environment, is there still interest in this? I ask because I think the typescript version obviates the need for this, so let me know otherwise.

**Comment by cmontella** [comment]
One thing you can do to work in the Eve container is the following. First, run the Eve cointainer as normal:

```
docker run witheve/eve
```

Then get the ID of the running container:

```
docker ps
```

This will provide output like:

```
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS                    NAMES
c103e6053334        witheve/eve         "/bin/sh -c 'npm star"   28 seconds ago      Up 27 seconds       0.0.0.0:8080->8080/tcp   sharp_goodall
```

Use the indicated name in the following command:

```
docker exec -it [NAME] bash
```
In this case it would be `docker exec -it  sharp_goodall bash`. Now you'll be in a bash session within the container.
