### ISSUE TITLE
Old records stick around after reevaluation

### ISSUE THREAD

**Issue by alltom** [witheve/Eve#464]
I expected this program to have one button, one `div` that shows the current value of `now.year`, and one `div` for each time you clicked the button. That's almost right, except there are always 2 or more "Current year: XXX" `div`s visible at any time.

The year is 2011:
```
commit
  [#now year: 2011]
```

```
match
  [#now year]
bind
  [#div text: "Current year: {{year}}"]
```

Create a button that increments the year:
```
commit
  [#button text: "Hello"]
```

```
match
  [#click]
  now = [#now year]
commit
  [#div text: "You clicked at {{year}}!"]
  now.year := now.year + 1
```

**Comment by cmontella** [comment]
Yes, this does look like a bug, but it's fixed in ts-merge, so I'm going to mark this as fixed. ts-merge will be master in a little under a week.

Here is your program, updated with the new syntax:

The year is 2011:
```
commit
  [#now year: 2011]
```

```
search
  [#now year]
  
bind @browser
  [#div text: "Current year: {{year}}"]
```

Create a button that increments the year:
```
commit @browser
  [#button text: "Hello"]
```

```
search @event @browser @session
  [#click element: [#button]]
  now = [#now year]
  
commit @browser @session
  [#div text: "You clicked at {{year}}!"]
  now.year := year + 1
```

There's one material change I made to your program, and that's this line here: `[#click element: [#button]]`

Whereas before you searched for just `[#click]`. This would match whenever anything was clicked, not just the button. But constraining the element to be `[#button]`, then this block will execute only when that button is clicked. In a larger app with multiple buttons, you can give the button multiple tags to specify exactly which one is clicked e.g.

```
commit @browser
  [#button #button1 text: "Button 1"]
  [#button #button2 text: "Button 2"]
```

```
search @event @browser
  [#click element [#button1]]

commit @browser
  [#div text: "Button 1 was clicked"]
```

```
search @event @browser
  [#click element [#button2]]

commit @browser
  [#div text: "Button 2 was clicked"]
```

**Comment by alltom** [comment]
Thanks for the rewrite and explanation! I'm just starting to learn the new syntax this afternoon.

Small question, though: how do I save & recompile code in the ts-merge branch? In master, I pressed cmd+return.

**Comment by cmontella** [comment]
You can recompile with `ctrl/cmd + enter`, or recompile and refresh with `ctrl/cmd + shift + enter`

However, currently edits in the editor will not save back to the file, but that's on the way!
