### ISSUE TITLE
Boolean false evaluates to true

### ISSUE THREAD

**Issue by alltom** [witheve/Eve#465]
This Eve program works on ts-merge, except that the buttons always say "Locked". The problem is that `if locked then "Locked" else "Unlocked"` always evaluates to `"Locked"`, even if `locked` is `false`. I fixed it by writing `if locked = true then ...`.

It took quite a lot of digging to figure that out. Fingers crossed that your announcement this week is a database viewer, or something [Theseus](https://github.com/adobe-research/theseus)-esque. :)

---

# [Two-Man Rule](https://en.wikipedia.org/wiki/Two-man_rule)
## Model
Create two locks.
```
commit @model
  [#lock name: "Lock 1", locked: true]
  [#lock name: "Lock 2", locked: true]
```

Unlock locks when their key is turned.
```
search @event @model
  [#turn-key name]
  lock = [#lock name]
commit @model
  lock.locked := false
```

Emit an event when both locks have been unlocked.
```
search @model
  [#lock name: "Lock 1", locked: false]
  [#lock name: "Lock 2", locked: false]
commit @event
  [#all-unlocked]
```

## View
Display buttons for each of the locks.
```
search @model
  [#lock name locked]
  state = if locked then "Locked" else "Unlocked"
bind @browser
  [#button name, text: "{{name}}: {{state}}"]
```

When a button is clicked, turn its key.
```
search @event @browser
  [#click element: [#button name]]
commit @event
  [#turn-key name]
```

Display a crazy awesome message when everything's unlocked
```
search @event
  [#all-unlocked]
commit @browser
  [#h1 text: "The door is open!"]
```

**Comment by joshuafcole** [comment]
Hey Tom,

Thanks for posting. This is actually working as intended. That probably seems surprising at first, particularly for people with strong procedural backgrounds. The reason while the block succeeds is not actually because `false` evaluates to `true`, but because `locked` tautologically exists (or we'd never have reached the `if` in the first place!). Since we are a pattern matching language, conditionals are built around patterns. When you changed the `if`'s body to `locked = true`, you gave us a more interesting pattern to work with, which matched only when `lock` was `true`.

Along with being more powerful in pattern-land, this also lets us neatly sidestep the issue of falsiness. Unlike a language such as JavaScript, where `undefined`, `false`, and `0` evaluate to `false` (leading to all sorts of interesting to debug errors), we require explicitness.

Hope that clears up the confusion, though if you're interested in debating this decision specifically or the semantics in general we'd love to hear from you over on the [mailing list](https://groups.google.com/forum/#!forum/eve-talk).

**Comment by ibdknox** [comment]
As an aside, it's probably worth erroring in this case - it never makes sense to have a bare identifier in an if branch.

@alltom great work on Theseus - I've followed it since it first came out. :) Your hopes should be answered... and then some with the release.
