### ISSUE TITLE
It's not clear what sort of action the equality operator is driving

### ISSUE THREAD

**Issue by JoeArizona** [witheve/Eve#470]
The first example in the Record section of the Syntax Reference reads:

> people = [tag: "person" age: 30 address]

What does the `people =` part do? It looks like the sort of implicit (and unclear) action of traditional programming languages, but it's not one of the three Eve actions (search, bind, or commit). I assume it creates a variable or object called `people`, but this isn't stated. In the lingo of conventional programming languages, it might be a variable binding, but it's not an Eve bind. Do we need to create a named entity like "people" to get filtered data? It's handy when we want to refer to or pass that entity, variable, or function later on in a program, but if all we want is to see some data, maybe in Eve we shouldn't need to create a named entity. In any case, whatever kind of action this is should ideally be accounted for in the specification of the Eve actions. 

I think the unseparated elements in the brackets will also confuse learners (no commas or semicolons to keep things separate). And `address` is just hanging on the end, inconsistent with the others in not having a colon. I suggest making explicit what is being asked for. So if we want the addresses of all 30-year-olds, there should be a clear syntax that identifies what we want, separate from the filters. Maybe a keyword like report, e.g. `report: address`

**Comment by cmontella** [comment]
Hi Joe, thanks for your thoughts. I'll try to clear things up for you, and then change the docs based on your feedback.

> What does the people = part do?

`people = [tag: "person" age: 30 address]` is used in the context of a search action, so maybe that part needs to be clearer in the syntax reference. You would never write this statement on it's own, you would write it like so:

```
search
  people = [tag: "person" age: 30 address]
```

What this means is we're searching for the record `[tag: "person" age: 30 address]` and you are equating it with the variable `people`. This is equality, not assignment as in other languages. You can use the variable `people` as a handle on the record, allowing you to access properties or modify the record in a commit or bind action.

> Do we need to create a named entity like "people" to get filtered data?

No, you can just search for `[tag: "person" age: 30 address]`. and you can use the attributes that you pull into the record. For example:

```
search
  [tag: "person" age: 30 address]

bind @browser
  [#div text: address]
```

> I think the unseparated elements in the brackets will also confuse learners (no commas or semicolons to keep things separate). And address is just hanging on the end, inconsistent with the others in not having a colon.

You are right, this is a little confusing. We're trying to practice a style that makes it clearer, and I will update this doc to reflect that style. I try to keep all tags first, then all unfiltered attributes, and then put filtered values at the end of the record with commas after filtered values. e.g.

```
[#person #employee name address age: 30, height > 5, eyes: "brown"]
```

Which would be read "all persons who are also employees with name and addresses who are 30 years old, over 5 feet tall, and have brown eyes". Syntax highlighting also makes clearer which tokens are values and which are attributes.

> So if we want the addresses of all 30-year-olds, there should be a clear syntax that identifies what we want, separate from the filters. Maybe a keyword like report, e.g. report: address

I don't think that's actually too much of an issue, since the common case seems to be pulling in attributes and only filtering a couple. However, you could adopt a style of programming where you only filter attributes outside of a record e.g.

```
search
  [#person #employee name address age height eyes]
  age = 30
  height > 5
  eyes = "brown"
```

Or you could even only filter inside the record and use other attributes through dot syntax:

```
search
  people = [#person age: 30, height > 5, eyes: "brown"]

bind @browser
  [#div text: "{{people.name}} lives at {{people.address}}"]
```

Until we get more users and see how people try to use Eve, I think it's good to have all these options. If we start to see a lot of confusion, we'll definitely revisit the issue.

I hope this makes things a little clearer for you. I'll leave this issue open for now, and I'll close it when I update the relevant docs.
