### ISSUE TITLE
http example sends request twice

### ISSUE THREAD

**Issue by curioussavage** [witheve/Eve#483]
In the http example the request is sent twice when you press the button. In the quickstart example it says (in reference to a click event) that the record only exists for an instant but apparently it exists long enough that it gets returned twice.

**Comment by vickychijwani** [comment]
I think this may be because the `http` database [doesn't call the `InsertAction` constructor correctly on line 66][1]. Here's a debugger snapshot of the Action constructor call:

![2016-11-01-180153_2966x900_scrot](https://cloud.githubusercontent.com/assets/439616/19889892/9aeff3d2-a05d-11e6-8066-4baa0867a2cc.png)

From what I can tell, the call is missing the 5th argument (`node`), so it should be:

```javascript
actions.push(new InsertAction(e, "tag", "sent", undefined, undefined, [name]));
```

I have no idea how this made it past the TypeScript compiler though, since `node` is of type `string` but is set to an array. I could send a PR but my understanding of Eve internals is so limited, I'm afraid I'll break something :)

[1]: https://github.com/witheve/Eve/blob/436b4521a8afd5f9b207dfa9c0d4395995fc1b70/src/runtime/databases/http.ts#L66

**Comment by ibdknox** [comment]
Nice catch, let's turn that into a PR so it gets attributed correctly. :) Instead of using `e` as the node id, let's set it as `"http|sender"`

**Comment by vickychijwani** [comment]
@ibdknox thanks Chris! Will send it over.

But does this mean all the other calls are incorrect too? (except system.ts)

```sh
> git grep "new InsertAction"
databases/node/http.ts:            actions.push(new InsertAction(e, "tag", "sent", undefined, [name]));
 databases/node/server.ts:      new InsertAction(requestId, "tag", "request", undefined, scopes),
 databases/node/server.ts:      new InsertAction(requestId, "url", request.url, undefined, scopes),
 databases/node/server.ts:        actions.push(new InsertAction(headerId, key, request.headers[key], undefined, scopes));
 databases/node/server.ts:      actions.push(new InsertAction(requestId, "headers", headerId, undefined, scopes))
 databases/node/server.ts:          actions.push(new InsertAction(bodyId, key, body[key], undefined, scopes));
 databases/node/server.ts:      actions.push(new InsertAction(requestId, "body", body, undefined, scopes))
 databases/node/server.ts:          actions.push(new InsertAction(e, "tag", "sent", undefined, [name]));
 databases/system.ts:      new InsertAction("time|tag", "time", "tag", "time"),
 databases/system.ts:      new InsertAction("memory|tag", "memory", "tag", "memory"),
```

**Comment by ibdknox** [comment]
looks like the server.ts ones are. The system.ts ones are ok.

**Comment by vickychijwani** [comment]
@ibdknox I'm not sure what change to make in server.ts - it looks like the `id` argument is correct but the 2nd argument (`e`) is missing? What's the entity in this case?

**Comment by vickychijwani** [comment]
Except the last call in server.ts, that one doesn't have an id again, so I could maybe make it `"response|sender"` or something like that.

**Comment by ibdknox** [comment]
like you said, I'm not sure why the TS compiler didn't blow up about this. The reason these are wrong is that I added the id param as the first param, previously it was only `e, a, v, node, scope`. So the server.ts ones are all missing the first param, which is the action's id. Because these actions are short-lived and only used for outside interactions, the id isn't particularly important here, but it should still have one

**Comment by ibdknox** [comment]
requestId, bodyId, and headerId are all entity ids there
