### ISSUE TITLE
Can't use trig functions

### ISSUE THREAD

**Issue by wcbarksdale** [witheve/Eve#513]
Running this (slightly modified from http://docs.witheve.com/handbook/math/sin/):
```
search
  y = sin[degrees: 90]
  x = sin[radians: 3.14 / 2]
  
bind @browser
  [#div text: "y is {{y}}"]
  [#div text: "x is {{x}}"]
```
Result:
```
y is NaN
x is NaN
```
Same for cos.  When I try tan, I get an editor error "There's no definition for the function tan".

For what it's worth, the clock example works for me but I haven't tried editing it.

**Comment by Cormac-Williams** [comment]
Hi wcbarksdale,

I've been digging into the math providor in order to add some more functionality, pull request should go in some time over the weekend. But I can push a temp version to my repo that fixes these if that helps.
 
The error for the Tan function is because it doesn't seem to be actually there :-),
The others because Degrees and Radians are missing as attributes in the function. If you use angle: it should work.

Regards,
Cormac.

**Comment by olafleur** [comment]
And the attribute for the `abs` function (absolute function, which is not a trig function) is `value` .
For example : 

`y = abs[value: 90]`

Which will give

`y is 90`

and

`y = abs[value: -3]`

will give

`y is 3`

**Comment by olafleur** [comment]
For the trig function, what is the desired public API @ibdknox @joshuafcole ?

Should we get rid of `angle` (which is degrees by default) or leave it for backwards compatibility (clock sample, for example) ?

The idea (according to the doc) is to be able to use `radians` and `degrees` as wished, right?

**Comment by joshuafcole** [comment]
I think we want to move these (and the clock example) to using
radians/degrees as optional parameters here and remove the legacy angle
option. To be polite, we can consider leaving it in for a week or so with
it passing a deprecated comment back to the client. Those functions predate
the new docs and haven't been updated to match yet.
