### ISSUE TITLE
Create an Electron app

### ISSUE THREAD

**Issue by Tiagojdferreira** [witheve/Eve#519]
I recently found out about Eve and I must say the idea looks pretty neat. After playing around with it I quickly realized that you can not use this repo as a true editor in the sense of opening and editing files in your local disk. That made me think that moving this into an [electron](http://electron.atom.io/) app would be awesome.

The two main advantages of doing so would be:
* distribution of apps (no need for node, npm, etc. for non web developers)
* Access to node server, allowing you to open files with file system from the app
* Access to [electron APIs](http://electron.atom.io/docs/api/)

I quickly tried to make the project run as an electron app, but I did not manage, but I would be more than willing to put some more time into it if there is an interest in it.

**Comment by tbodt** [comment]
Electron is shit.

You have to bundle an entire copy of Chrome into the app, inflating the size of the app by 100 MB.

You have to use the V8 Javascript engine, which prioritizes performance over memory leaks and will cause the app to consume hundreds of megabytes of memory.

You have to deal with performance issues caused by the fact that everything is Javascript. Like, when you resize a window, it takes a few milliseconds for the content to resize.

Don't.

**Comment by ibdknox** [comment]
@tbodt The dismissive and aggressive tone of this post is not befitting of the inclusive community we want to build around Eve. Please be respectful and considerate of others when providing feedback. There is nothing wrong with the suggestion and nothing about having an Electron app as part of the ecosystem that would hurt Eve itself.

**Comment by tbodt** [comment]
@ibdknox Entirely true, I should probably delete that comment and put it on Reddit somewhere.

**Comment by Tiagojdferreira** [comment]
Moved discussion to google group https://groups.google.com/forum/#!topic/eve-talk/-NEWccRdr_g
