### ISSUE TITLE
Click event doesn't last long enough for values derived from committed records to be matched against?

### ISSUE THREAD

**Issue by btheado** [witheve/Eve#536]
I'm having trouble explaining this issue. Hopefully the code is simple enough
to follow.

On a click event, I'm committing a record (`[#item]`) and binding a record
(`[#add-item]`). The committed record has a derived value `parent` bound to
it. I have a search on the combination of the parent derived value of the 
committed record and the `[#add-item]` record. I was thinking the click event
should keep the `[#add-item]` record alive long enough for that derived
value to be searched with. But based on the behavior that is not the case.

Expected results on each click of "add new"
- `i: <x>, p: <y>`
- `#add-item: b:<x>`
- `#add-item: b:<x>, p:<y> - it works!`

Actual results (i.e. the last item from the above list is missing):
- `i: <x>, p: <y>`
- `#add-item: b:<x>`

Derived values for representing a binary tree.
```
search
  item = [#item binidx]
bind
  item.parent := floor[value: (binidx - 1) / 2]
  item.child1 := binidx * 2 + 1
  item.child2 := binidx * 2 + 2
  item.level := floor[value: log[value: binidx + 1] / log[value: 2]]
```

Flat display of the items...no hierarchy needed for this simple example
```
search
  [#item binidx parent]
commit @browser
  [#div text: "i:{{binidx}},p:{{parent}}"]
```

Something to click to create a new item
```
commit @browser
  [#div #add-new text: "add new"]
```

On click, find unused binidx and create the item
```
search @event @browser
  [#click element: [#add-new]]
search
  binidx = if [#item] then count[given: [#item]] else 0
bind
  [#add-item binidx]  // So this event can be reacted to elsewhere
                      // and the derived values can be used
                      // I'm using bind instead of commit so I don't
                      // have to manage the lifetime myself
commit
  [#item binidx]
```

In order for this to match, the #add-item still needs to be around which means the #click needs to still be around. The #item needs to be in the db and its "parent" derived value available.
I expect this to work, but it doesn't. Workaround would probably be to use commit instead of bind for #add-item above and then delete it here.
```
search
  [#add-item binidx]
  [#item binidx parent] // somehow 'parent' reference prevents match
commit @browser
  [#div text: "#add-item: b:{{binidx}}, p:{{parent}} - it worked!"]
```

This one, without the derived value does work
```
search
  [#add-item binidx]
  [#item binidx] // without parent reference it matches fine
commit @browser
  [#div text: "#add-item: b:{{binidx}}"]

```

**Comment by cmontella** [comment]
I think you understand this pretty well, you've touched on the reason this isn't working:

> In order for this to match, the #add-item still needs to be around which means the #click needs to still be around. The #item needs to be in the db and its "parent" derived value available.

The problem is that a `#click` only lasts an instant. What's happening is the user clicks the button, Eve creates a `#click` record, the block in question matches and binds an `#add-item`. But then in the next instant, Eve removes the `#click`, which of course removes the `#add-item`.

In your comment, you note "I'm using bind instead of commit so I don't have to manage the lifetime myself". What do you want the lifetime to be?

**Comment by btheado** [comment]
What defines an instant? Only for the actions inside the block in which it was searched?

If I change it from a bind to a commit and then change the 2nd to last block to this then it works the way I want:

```
search
  a = [#add-item binidx]
  [#item binidx parent]
commit
  a := none
commit @browser
  [#div text: "#add-item: b:{{binidx}}, p:{{parent}} - it worked!"]
```

I was thinking that the "downstream impacts" on other blocks of the `bind [#add-item binidx]` would be followed through before the click is removed.

So maybe the rule I should keep in mind is that a commit is the only action that can have an impact outside of a block containing the click event.

**Comment by ibdknox** [comment]
You are correct that other blocks should have the chance to react. Seems like something else is going on here.

**Comment by ibdknox** [comment]
Sorry for the delay on this. So I was wrong, this isn't a bug in Eve per se, but it seems like we need to do a little thinking on what this pattern would typically look like.

It's easiest to see what's going on by drawing out the timeline:

```
T0: 
      + [#click]
T1: 
      + [#add-item binidx]
      + [#item binidx]
      - [#click]
T2: 
      + [#item].parent
      - [#add-item]
T3:
      Parent is now available but add-item is gone
```

Changes are only visible in the following time step. So when the `[#item]` record is created, the block that adds parent won't see it until the next time step. By the time it has a chance to add parent, the `[#add-item]` record will be removed since clicks are removed after one time step. Most of the time none of this matters, but the way this is formulated it unfortunately does. A time step visualization would be insanely helpful here, but this is something we should think more about to see if there's either a more intuitive pattern or if there's some adjustment we could make to the semantics to make this better.

> So maybe the rule I should keep in mind is that a commit is the only action that can have an impact outside of a block containing the click event.

In general, that's the rule I follow. Binding to events is like an impulse and so the only time it makes sense is if you're going to use that to immediately commit something else. The issue is that all the data has to be available during the time the impulse is alive, so you can't rely on other blocks.

**Comment by ibdknox** [comment]
Since this isn't an issue that has an action associated to it, I'm going to close for now. Sorry again about the wait.

**Comment by btheado** [comment]
Thanks for the explanation. Since then I came up with a workaround. Instead of querying against the parent field (which is a derived field) of the newly inserted item, I changed it to query against the child1 and child2 derived fields of previously committed items.

So instead of searching for the new item's parent:
```
search
  [#add-item binidx]
  p = [#item binidx parent]
commit
  p.tag - = "sorted"
```

I instead search for an existing item for which this new item is child1 or child2 (which means it must be the new item's parent, of course):
```
search
  [#add-item binidx]
  [#item binidx]
  parent = if      p = [#item child1: binidx] then p
           else if p = [#item child2: binidx] then p
commit
  parent.tag -= "sorted"
```

Also in my code I encountered the same issue when I wanted to automatically "expand" the ancestors of the newly inserted item (to ensure a new item is always visible in the tree). The ancestors attribute is a (recursively defined) derived field, so my first attempt didn't work. I had to match the parent using the same child1, child2 trick as above and then find the parent's ancestors and "expand" the parent and the ancestors. So it was a little more complicated than my first attempt:

```
search
  [#add-item binidx]
  [#item binidx]
  (a1,p) = if      p = [#item child1: binidx] then (p.ancestors,p)
           else if p = [#item child2: binidx] then (p.ancestors,p)
  ancestors = a1
  collapsed = [#item #collapsed binidx: ancestors.binidx]
commit
  collapsed.tag -= "collapsed"
  p.tag -= "collapsed"
```
