### ISSUE TITLE
Records copied to @browser database from another database are not displayed as HTML elements

### ISSUE THREAD

**Issue by thSoft** [witheve/Eve#537]
E.g. these two blocks:
```
commit
  [#div text: "foo"]
```

```
search
  div = [#div]
bind @browser
  [#div children: div]
```
produce `<div/>` instead of `<div><div>foo</div></div>`.

**Comment by joshuafcole** [comment]
Hey @thSoft:

This is actually not doing quite what you think. Rather than copying every attribute about the divs in the default database into @browser, it only adds the id of those divs as the `children` attribute of the parent container. Because no attributes exist for those ids in the @browser database, they don't show up.

If you want to copy the entire record over wholesale, you can do it one of two ways. If there are a small number of statically known attributes, you can copy them manually:

```
search
  div = [#div text]

bind @browser
    div <- [#div text]
    [#div children: div]
```

If you have a whole lot of attributes or unknown ones, you can use the lookup forms (which deals with the attribute--value pairs of records directly)

```
search
  div = [#div]
  lookup[record: div, attribute, value]

bind @browser
  lookup[record: div, attribute, value]
  [#div children: div]
```


We know this can be a sticking point for users, since for the most part thinking of records as a single "object" fits our model well. Unfortunately, making that actually be the case has a lot of unfortunate gotchas as well. We plan to help users here by making the tooling intelligent enough to catch this pattern and show the correct solution.

If you have any other thoughts on how to improve that experience we'd like to hear them.

Josh

**Comment by thSoft** [comment]
Thanks for the clarification! Maybe we should transform this issue about documenting and implementing tooling support for such cases?
