### ISSUE TITLE
Ordering bug in renderer

### ISSUE THREAD

**Issue by cmontella** [witheve/Eve#570]
Sort students alphabetically by grade (some test data is committed below)

```
search
  [#student name grade teacher]
  index = sort[value: name, per: grade]
  
bind @browser
  [#div grade children: 
    [#h3 sort: 0, text: "Grade: {{grade}}"]
    [#div sort: index, text: "{{index}} {{name}}"]]
```

The output is:

```
1 Damion

### Grade: 12

2 Gretchen
3 Octavio
4 Pa
```

The expected output is:

```

### Grade: 12

1 Damion
2 Gretchen
3 Octavio
4 Pa
```

Despite being told it's `sort: 0`, the h3 is ordered at position 2 in the div. If I change it's `sort: -1`, then it appears in the right spot.

---

Commit some test data

```
commit
  [#student name: "Damion", grade: 12, teacher: "Mrs. Purple", GPA: "3.8"]
  [#student name: "Gretchen", grade: 12, teacher: "Mrs. Yellow", GPA: "2.8"]
  [#student name: "Octavio", grade: 12, teacher: "Mrs. Purple", GPA: "3.4"]
  [#student name: "Pa", grade: 12, teacher: "Mrs. Yellow", GPA: "3.5"]
```

**Comment by pingram3541** [comment]
Interesting, an index value of 0, 1, or 2 all result in the indexed position of 2.

When I read the docs about [sort](http://docs.witheve.com/handbook/general/sort/) it details that indexing begins at a positive int so wouldn't an index value of 0 or even -1 for that matter be invalid?  Also, since the H3 tag has an auto-index value less than that of the div tags, one would expect it to render first?

**Comment by joshuafcole** [comment]
I'm pretty sure this is an off-by-one (the renderer was written long before
we switched to 1-indexed, and I don't recall if it's been updated). Will
investigate.
