### ISSUE TITLE
Proposal to integrate CSS blocks into Eve documents

### ISSUE THREAD

**Issue by dwsmorris** [witheve/Eve#579]
1) Change the existing _block_ option to _Eve_ and add a _CSS_ option to the new insertion menu.

![insertblock](https://cloud.githubusercontent.com/assets/6561577/20458365/5fe64592-ae9b-11e6-98aa-4d53d27b61d5.png)

2) CSS blocks are rendered distinctly in the editor. CSS is applied to the active application.

![styled](https://cloud.githubusercontent.com/assets/6561577/20458376/96df8130-ae9b-11e6-86c7-ab4a0d4e7783.png)

3) CSS blocks can be enabled/disabled by tickmarks, just like other code blocks.

![unstyled](https://cloud.githubusercontent.com/assets/6561577/20458384/cd3ad9f0-ae9b-11e6-89ae-41da2c85b479.png)

**Comment by nmsmith** [comment]
I've been applying CSS styles using Eve blocks. It's not too different.

![image](https://cloud.githubusercontent.com/assets/909604/20459958/3d7f2c2a-af28-11e6-9a85-dcf643fd31a5.png)

Seeing as Eve is not about HTML and CSS, I'm not sure that tightly integrating the editing experience with those technologies is a good thing.

**Comment by cmontella** [comment]
This is a great idea, although I agree with Nick that maybe this doesn't belong in the main editor, but it might be better served as a plugin/extension (what that means we also have to talk about.

Ultimately, we are demoing and using html/css as a convenience, but there might be a better ui/styling model for Eve. So we don't want eve to be synonymous with writing web apps.

However, a lot of our first users will be web devs, and if they want to write css because they're comfortable with it, this proposal makes that very easy.

Other thoughts?

**Comment by dwsmorris** [comment]
Regarding Nick's example - yes, for simple styling, it's much better, or should I say 'nicer', to use inline-styles as already supported via Eve syntax.

However, this has severe handicaps. How do I create a rollover effect? You cannot simulate some critical styling features like :hover and :active, and you don't have access to the convenience of CSS animations among other things.

This debate has gone on already in the React world. Being able to do everything in one language is compelling. [Radium](https://github.com/FormidableLabs/radium) is the poster-boy of this approach. With time, the community has moved away from this though (including the Radium project itself), for a more pragmatic approach as typified by [Aphrodite](https://github.com/Khan/aphrodite). This injects raw CSS into the DOM behind the scenes, so you essentially have access to the whole browser CSS styling engine and don't have to simulate it (with inevitable compromises).

I'm a developer, and primarily interested in being able to use Eve practically. So for me to get up and running quickly, only two things are currently missing. A styling solution and way to generate an application distributable. This feature makes my experience much nicer - but then again, I have a very focused viewpoint. :)

**Comment by nmsmith** [comment]
I agree with Corey that it would work great as some kind of editor plugin. R.e. this, there would actually be a lot of use-cases for an editor feature that allows a user to design and embed a "view" over a set of records. In this situation, the interface you've prototyped would be a view over a `#css` record which the renderer reads to add CSS to the webpage.

Designing these kinds of views would be easy in Eve because it's already a reactive language, but it would probably be helpful to have support for two-way data binding so that altering the CSS through the view automatically updates the backing record without requiring any coding.

Other use-cases for this "custom view" feature would be allowing the user to embed custom data visualisations into an Eve document, or interactive widgets that manipulate data like in Jupyter and Mathematica.

**Comment by nmsmith** [comment]
I made an example of how to implement a custom view. It took me about 2 minutes! All we require is that:

- Instead of binding the textarea to the browser, we can bind it to a place in the editor.
- The code that creates the DOM also reads from the `#css` record to add the CSS to the webpage.

```
commit @browser
  [#textarea #css-view]
```

```
search @browser
  view = [#css-view]
bind @browser
  view.style := [width: 300, height: 50, background-color: "yellow"]
```

```
search @browser
  view = [#css-view value]
bind @browser
  [#css text: value]
bind @view
  [#value value]
```

**Comment by joshuafcole** [comment]
This is in release 0.2.3! Thanks again to @dwsmorris for all the hard work. :)
