### ISSUE TITLE
Document @browser source-of-truth model

### ISSUE THREAD

**Issue by nmsmith** [witheve/Eve#587]
The semantics of bind informs us that bound records remain in the database as long as the constraints in the search component of the block remain met. Unconditional binds should therefore correspond to immutable values. Unfortunately, this is not happening with bound input elements. The following code snippet illustrates the problem:

```
bind @browser
  [#input value: "immutable value"]
```

The user is somehow able to "overrule" this binding when they type within the input element. This problem applies to textareas and probably other elements as well.

**Comment by joshuafcole** [comment]
Hey Nick,

What you're seeing stems from two things:

The first is that the @browser DB is  setup as an authoritative mirror to the current state of the DOM. That is, whatever value the DOM has, the @browser DB reflects. Since those inputs aren't readonly, the user adjusting their value causes some blocks in @event to re-run, updating @browser.

The second is where it gets a little confusing. We've made a semantic compromise for performance reasons. Rather than *actually* re-running each block every change (which is currently very expensive) we re-run blocks only when it's possible that an input to the block has changed. In this case, your block has no inputs and thus never gets re-run.

Unfortunately (as you may have surmised) the times when an input to a block changes are a subset of the times when the block could have effected the programs output. The correct way to think about Eve blocks right now is not as always being run, but instead run when something they could conceivably subscribe to changes.

In practice, this *usually* works out. If you were dynamically updating the inputs value, the block drawing the input would update (seeing the value change). It does however open us up to several of these strange edge cases.

We're by no means married to this decision and know it can be a sticking point. Even if we can't find a proper semantic fix here, there are a lot of things we can do to alleviate the symptoms which we plan to prioritize as usage patterns start to emerge. To start with we plan to deprecate and eventually remove searchless binds, since they don't function any differently than searchless commits and are significantly more likely to catch users off-guard.

With your consent, I'd like to pivot this issue to track documentation about this behavior.

As ever, if you have any thoughts on how we could improve this please let us know.

**Comment by nmsmith** [comment]
Thanks for the explanation. Feel free to make this issue about documentation.

Would it be possible to change things such that a block with a bind action subscribes to both changes to its input and changes to its output? So that when either of the two change, the block re-runs to "fix" the output. My understanding is that this would cause an automatic revert of any changes made through the browser interface.

Ideally though (as you probably agree), the Eve database would be a primary source of truth, and the DOM would be a view over the database. Following the MVC pattern you would interact with the browser through controllers that mutate the database, which then re-renders the view / DOM.

If this is not feasible, perhaps it is motivation to integrate Eve into a browser engine!

**Comment by joshuafcole** [comment]
Sorry for the late response, I missed your comment. This seems like a beneficial behavior to consider, but it has some performance and memory impacts. I'll float it by @ibdknox and we'll see if there's potential to doing something like this in the short-term.

W.r.t. the Eve database being the source of truth, it seems to me like it'd be pretty unpleasant for a user to always have to make a block to update inputs based on events when they want a user to be able to type freely. Further, when Eve is running on the server that's an untenable position to be in due to latency issues. It can cause a very poor typing experience for the user when each of their keystrokes has to roundtrip before it can commit. Because of that it seemed like a better approach to make the value represent the enduser's input--that way the programmer can override any invalid values when he sees them in a validating block--without interrupting the user.

If you have other thoughts on how to alleviate that problem though, I'd love to hear them. It's an interesting space to explore.

**Comment by nmsmith** [comment]
> W.r.t. the Eve database being the source of truth, it seems to me like it'd be pretty unpleasant for a user to always have to make a block to update inputs based on events when they want a user to be able to type freely.

You wouldn't need to code up extra blocks for this. It would just be that instead of the browser sending a copy of its state to Eve, Eve would send a copy of its state to the browser. Browser events would be handled by Eve blocks which could be either built-in or (in the long term) library code -- the user won't have to touch them, unless they want to override default behaviour like you can do in JavaScript, at which point having access to the code is a useful feature!

> Further, when Eve is running on the server that's an untenable position to be in due to latency issues.

In this case I think you'd probably want a small Eve `@database` on the client that holds the browser state, and with which the server communicates. Coordination between client and server is a standard distributed programming problem which you guys say Eve is great at, so I leave that part to you ;)

Just my two cents.

**Comment by joshuafcole** [comment]
> Browser events would be handled by Eve blocks which could be either built-in or (in the long term) library code -- the user won't have to touch them

That's actually how it works right now, if you check `event.eve` :)

The distributed solution will certainly be possible, but feels like overkill for a lot of cases. Nonetheless, it's certainly a reasonable thing to request, and is worth revisiting once the work is in place to enable it.

**Comment by joshuafcole** [comment]
Pulling @cmontella in on this since it's a shortfall in our current docs.

**Comment by cmontella** [comment]
I'm going to close this here, and open an issue in witheve/docs to track this: https://github.com/witheve/docs/issues/42
