### ISSUE TITLE
+ should not concat strings

### ISSUE THREAD

**Issue by cmontella** [witheve/Eve#631]
For example

```
x = "foo" + "bar"
```

Then `x` should not be "foobar"

**Comment by Cormac-Williams** [comment]
Do you wish to it replace by an explicit string concatenation operator, if so what? Or is string interpolation the only way to go?

**Comment by joshuafcole** [comment]
Out of curiosity, what would differentiate the concatenation operator from
string interpolation? Internally, the concatenation operator is already
implemented, but we chose to only expose interpolation add its interface
because it seemed like a superset of functionality with a nice ux.

**Comment by Cormac-Williams** [comment]
No particular difference. I was asking because I was considering putting together the pull to handle this.
There was discussion with @ibdknox on a recent pull re: this specific subject, my opinion as a programmer is that I like to have both, there's not much in it in terms of typing, it's more a new language making me learn something new. Since Eve is already so different that may not 

If you remove the current ability to add strings with the Math.ts Add function and don't replace with another operator then any

search
  x = "foo" + "bar"
commit @browser
[#div text:x]

block would filter, I'm fairly sure that would irritate some experienced programmers new to Eve ;-)

In fairness I had a play and have found a case of unexpected behaviour from the current concat version.

The following 

```
commit
  [#test type:"Num - Num" x:1 y:1]
  [#test type:"Str - Num" x:"1" y:1]
  [#test type:"Num - Str" x:1 y:"1"]
  [#test type:"Srt - Str" x:"1" y:"1"]
  [#test type:"Srt - Str" x:"0" y:"1"]
```

```
search
  tmp = [#test x y]
bind
  tmp.result := x + y
```

```
search
  tmp = [#test x y result]
bind @view
  [#value value:"{{tmp.type}} {{tmp.x}} + {{tmp.y}} = {{tmp.result}}"]
```

yields
Srt - Str 0 + 1 = 01
Num - Num 1 + 1 = 2
Str - Num 1 + 1 = 2
Num - Str 1 + 1 = 2
Srt - Str 1 + 1 = 2

Regards,
Cormac.

**Comment by joshuafcole** [comment]
String interpolation and templating seem to be increasingly popular in
languages and frameworks used by webdevs these days, though I don't know
what the natural exposure for systems and native programmers is like here.
That said, I'm unsure that overloading `+` to do string concatenation as
well would be the right move. By making it similar but slightly different
we invite new users to trip over the little differences like lack of
implicit coercion. If, to avoid that, we chose to make it a separate
operator, you'd have to learn something new anyway, which takes more
keystrokes and is a likely harder to read.

Once @error is set up (which is slowly increasing in priority as we run
into more and more cases where it can seriously improve usability), I think
the filtering will be less of an issue than it is now, where it silently
throws away your problems without warning.

All that said, I'm open to considering the alternative, but I'd like to
start from the position that adds the least and watch to see if new users
struggle here, necessitating some alternative. Thoughts?

**Comment by cmontella** [comment]
Just wanted to clear up that the important part of this issue isn't implicit conversion, it's that + shouldn't be doing any concatenation at all.

**Comment by Cormac-Williams** [comment]
Pull https://github.com/witheve/Eve/pull/743

Regards,
Cormac.
