### ISSUE TITLE
Building a blog

### ISSUE THREAD

**Issue by ccorcos** [witheve/Eve#695]
I'm going to be building a simple blog, but it thought it might be fun to use this as an opportunity to play with eve. I see that in a recent release, we can now deploy application which is cool, but I'm curious your thoughts on what's missing before we can start building more complete applications.

I'd like to be able to login and submit posts through a web ui, for example.

**Comment by cmontella** [comment]
One thing that will sorely be missing here is security; Eve doesn't make any guarantees yet about keeping your password safe and secure. Now, you might be able to use a third party authentication service to do login, but I still wouldn't trust any of my data.

Another thing you'll probably miss is persistence. If you update your blog via this web portal, then when the Eve server crashes, all the posts you created will be gone, since they're currently only stored in memory.

Those are just a couple off the top of my head that would hold you back.

**Comment by ccorcos** [comment]
Alrighty then. Sounds like a mountain of work ahead of you guys! When are you going to start hiring?

**Comment by cmontella** [comment]
Yeah, there's a lot of work ahead, and we'll be needing people to help, that's for sure. Keep an eye out in 2017, we'll make any announcements on the blog.

**Comment by ccorcos** [comment]
Sounds good. Exciting work you guys are going.
