### ISSUE TITLE
Cant set the attribute value 

### ISSUE THREAD

**Issue by massanchik** [witheve/Eve#723]
[Here is my first little app.](https://gist.github.com/anonymous/8de8c06d0e576569ffa1275c97f9d0cf)
Idea is you click the button and the language attribute toggles.
But after click "handler" fires, attribute seems have no value at all.
[#lang v: ?]
And can I some how "console.log" records or you have some other debugging features?

**Comment by wilk** [comment]
@massanchik 

Here's the difference between `bind` and `commit`: http://docs.witheve.com/handbook/bind/

Quoting the **Tips** section:

> When you want to display data in an interface element like a #div, a bind is usually the more appropriate choice compared to a commit. A bind will keep the interface element always up-to-date, whereas a commit will leave lingering elements that no longer reflect the current state of the program.
> 
> When searching for an event like a #click, a commit is usually more appropriate than bind. When an event occurs, a record representing the event is added to a database. That record exists for exactly one “instant”, and then it is removed from the database. During that “instant”, any block searching for that event will be satisfied and can execute a bind or commit action. If you bind on the event, then the result will disappear as soon as the event does. However, if you commit on the event, then that result will persist after the event has been removed.

Turns out you've used bind when a commit was necessary, like in the click event handler:

```eve
bind @session
  lang.v := new-lang
```

Instead of:

```eve
commit @session
  lang.v := new-lang
```

Another thing is searching in the right database.
Look at the following code of the click event handler:

```eve
search @event @session
  [#click element: [#btn-main]]
  lang = [#lang]
  new-lang = if lang.v = "en" then "ru"
             else "en"
```

You're looking into the `@event` and `@session` databases (needed by the `#click` and `#lang` records) but one more is missing: the `@browser` database because of the `#btn-main` record.
When no database is provided, the local `@session` database is used.

At least, this is what I've understood from the documentation.
If I'm wrong, please correct me.

Here's the working gist: https://gist.github.com/anonymous/c71b726e583f0e1b1267a04a795e7b26

**Comment by cmontella** [comment]
@wilk has the right fix, but I wanted to chime in about the second part of your question:

> And can I some how "console.log" records or you have some other debugging features?

Right now, the most prevalent way to print debug info is by binding it to the browser in a div, which you already know how to do. But there is another mechanism, called "views", which allow you to visualize data right next to a block.

For example, you can print a string with the `#value` view. The following block will print the current seconds:

```eve
search
  [#time seconds]

bind @view
  [#value | value: seconds]
```

Views aren't well documented and a little buggy, but you can see their source here for a better idea of how they work: http://play.witheve.com/#/examples/view.eve

**Comment by massanchik** [comment]
Thanks, @wilk!
So, to change record attributes we should use commit instead of bind. 
Or it's just @browser interaction stuff?
I looked at [docs](http://docs.witheve.com/handbook/set/) and there is
```
bind
  student.age := age
```

**Comment by massanchik** [comment]
@cmontella thank you for advice!
I actually very excited about this project. 
It's quite intuitive way to design a piece of software.

**Comment by cmontella** [comment]
@massanchik 

The key here was the interactivity. `commit` versus `bind` is all about lifetimes, and choosing which you use depends on how long you want the records to last. Committed records last forever, until they are removed manually. Bound records last only as long as their matched records. 

With that in mind, let's look at the original block:

```eve
search @event @session
  [#click element: [#btn-main]]
  lang = [#lang]
  new-lang = if lang.v = "en" then "ru"
             else "en"

bind @browser
  [#div text: "lang {{lang.v}}"]
```

Since you bound the div, it will last as long as the records that match the search, one of which is a `#click`. Click records are special, because they only last an instant and then are removed from the @event db. Thus, any records bound with a click only last an instant as well. 

When you commit the div instead, you don't care about how long any of the matched records exist. The click comes, the div gets committed, the click disappears, but the div persists. Here are some docs explaining this in a little more detail:

http://docs.witheve.com/handbook/bind/
http://docs.witheve.com/handbook/commit/
