### ISSUE TITLE
Eve functions, namespaces and modules

### ISSUE THREAD

**Issue by wilk** [witheve/Eve#769]
Hi again,

another question on Eve regarding functions.
Is there a way to create custom functions, like `lookup` and `floor`?
If so, do I need to commit them into a custom database or is there a way to specify a namespace?

Talking about namespaces: is it possible to define custom modules, maybe defined in different markdown files?
In huge applications, different files are used and so having a way to import/export modules it's a must.
Is there a proof of concept for that?

Thanks.
Wilk

**Comment by joshuafcole** [comment]
You can find the current draft documentation on adding new primitive expressions and databases (custom modules) to the language here: 
https://gist.github.com/joshuafcole/52f706e0e838b3fb7536814de8879af0

I was holding off on responding to this since I'd hoped to have the runtime refactor wrapped up earlier. We've paid a lot of attention to extensibility with it and the interfaces are significantly more elegant. Basic support is even in place to load in function and watcher libraries via npm packages.

My advice is to hang in there until we get this wrapped up before trying to extend Eve, but you're welcome to use the above guide in the interim if you have an urgent desire to get started.

**Comment by wilk** [comment]
Thanks @joshuafcole 

Actually, I was wondering if it could be possible to do it just with Eve, not with another language like TS/JS.
Does Eve rely on TS/JS for external dependencies?

Cheers,
Wilk
