### ISSUE TITLE
"Unable to find file" on macOS

### ISSUE THREAD

**Issue by thSoft** [witheve/Eve#781]
* Eve 0.2.3
* macOS Sierra 10.12.3
* node v4.4.7
* npm 2.15.8

```
$ npm install -g witheve
$ touch foo.eve
$ eve foo.eve --editor
Eve is available at http://localhost:8080. Point your browser there to access the Eve editor.
```
If I navigate to http://localhost:8080, the following error message is output:
```
Unable to find file '/Users/thsoft/foo.eve' in 'root'
```
The browser redirects me to the examples (http://localhost:8080/#/examples/quickstart.eve).

**Comment by joshuafcole** [comment]
Hey @thSoft:

The current custom project support is pretty rough (it's going to be overhauled for user-friendliness once we finish refactoring the runtime). In order to work with a custom project (instead of the built-in example workspace) you'll need to create a `package.json` file in your working directory. We do this for compatibility with npm, to keep our options open for users sharing modules in the future.

If touching that file and then rerunning as you were doesn't work, please let us know!

**Comment by thSoft** [comment]
Thanks for the quick reply! After creating an empty `package.json`, Eve works properly. However, I propose either creating this file automatically or on confirmation if it doesn't exist or failing and instructing the user to do so.

**Comment by joshuafcole** [comment]
Agreed that the current experience is bad, however we do want the first user experience to drop them into the examples workspace. However, we need to *minimum* include some verbiage about that (and how to switch into a custom project) in the console, and better yet as you say provide a way to do that automatically. Let's close this bug and link it into a new one that tracks improving the Eve CLI.
