### ISSUE TITLE
Quickstart tutorial problems (possible websocket error)

### ISSUE THREAD

**Issue by ianchanning** [witheve/Eve#876]
I've done perhaps two things with the Quickstart tutorial and they both seem to fail.

I'm using:

* Windows 10 64-bit
* Firefox 54
* Chromium 59

I went to this URL: http://play.witheve.com/#/examples/quickstart.eve

Initially the page displays the 'Hello World' text.

![2017-08-05 11_56_12-store](https://user-images.githubusercontent.com/233318/28994718-4b971ee4-79d5-11e7-9e24-6cf70956260f.png)

1. If I then click 'Run', the 'Hello World' text disappears, but I can get it to reappear with 'Reset' - this seems counterintuitive to me

![2017-08-05 11_56_30-store](https://user-images.githubusercontent.com/233318/28994722-66081e18-79d5-11e7-9d2d-e8512c522d87.png)

2. (I now realise this is a duplicate of #871) If I then untick **and retick** the first block of code I then can't get the 'Hello World' text to appear by clicking either the 'Reset' or the 'Run' buttons.

![2017-08-05 11_57_17-eve](https://user-images.githubusercontent.com/233318/28994725-6d9d0d28-79d5-11e7-9889-4f49c4f74d99.png)

I'm getting a websocket console error, but the code runs in spite of this, and clicking 'Run' doesn't cause any further errors:

![2017-08-05 12_03_50-](https://user-images.githubusercontent.com/233318/28994787-ab7b63c8-79d6-11e7-82e9-4b9e13c3ffd9.png)

**Comment by timcombs** [comment]
see: https://github.com/witheve/Eve/issues/871

**Comment by ianchanning** [comment]
@timcombs Thanks for your reply - this indeed explains part 2, but it didn't explain part 1:

> If I then click 'Run', the 'Hello World' text disappears, but I can get it to reappear with 'Reset' - this seems counterintuitive to me

**Comment by joshuafcole** [comment]
Hey @ianchanning, #871, is indeed the root cause of both issues. Under the hood, enabling/disabling blocks adds a tag to the text of the document, which is then reparsed from scratch server side and recompiled. Unfortunately, this isn't marking the document dirty and optimizations that were made the month before last first check the document's dirty status to determine if a recompilation is needed. This is also gating the reset button.

We've elected to focus on getting the latest version of Eve (which has the same syntax and semantics, so no major changes) out rather than fixing the old one for a couple reasons:

1) The new version is several orders of magnitude faster than the old version in the worst case, more in better cases.
2) The editor for the old version was built expecting a complete separation of the editor and parser/compiler. This causes serious slowdowns on large documents and makes certain features we'd love to provide very difficult. Fixing that is tantamount to a rewrite of the editor, but given the performance of the latest Eve version if we're going to rewrite it we'd like to do so bootstrapped with Eve.

We'll be releasing more news about the latest version on the blog shortly. In the interim, I'd recommend using the editor primarily for debugging via the inspector and instead using the text editor of your choice, which won't have these issues.

**Comment by ianchanning** [comment]
@joshuafcole ok, thanks for letting me know. I'll close this then as it's purely a duplicate.

**Comment by ianchanning** [comment]
@joshuafcole  Plus very excited to hear the progress :)
