### ISSUE TITLE
Can't scroll down on any page on http://docs.witheve.com in either chrome or firefox

### ISSUE THREAD

**Issue by peey** [witheve/Eve#892]
For example, this page: http://docs.witheve.com/v0.3/tutorials/quickstart/

**Comment by joshuafcole** [comment]
I'll take a look this evening, thanks for letting us know.

**Comment by PallHaraldsson** [comment]
Hi, I have nothing to do with Eve officially. I'm just responding as I noticed this and find Eve very intriguing.

I'm sure this is not intentional, but happened because of some system update.

I did read about Eve at some point, I guess this page too, and implicate JavaScript in this. You used to be able to disable it in browsers, and then you could see the source and do stuff web designers (intentionally) tried to forbid, like right clicking and do view source.

EDIT: It _seems_ I actually disabled JavaScript, but it wasn't effective to see the page as indented. But CTRL+U still does the trick. I don't know could it be CSS?

In Firefox you can still do that with Ctrl+U. I did try the instructions here (but I guess I would need to reset the web browser): https://www.technipages.com/firefox-enable-disable-javascript 

```
        <script>
            (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
            (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
            m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
            })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

            ga('create', 'UA-74222157-2', 'auto');
            ga('send', 'pageview');
        </script>
        <script src="/js/highlighter-bundle.js"></script> 
        <script>
            window["eve-highlighter"].highlightAll();
        </script>
```

**Comment by joshuafcole** [comment]
No need to mess with JS! -- Just the CSS falling apart over time, sadly. The fix looks pretty simple, I just need to sit down after work and get it patched up.
